travis:
  secure:
    BINSTAR_TOKEN: oM08WyrnQRd4HBoS2GxGrwi7Uu+3jGo6+UHIEPNOkkkyOrU1sW0vj/1kAkv+MG7raCbtXzh8sPR41ZmAFruDGJRUPmLCTpewOvLb+CzXHCqUw9JHRFCaXnkjYY61DmEqsx2zZA8BZldi5L78mKpCfEQxFveKGhettM7Xmw1DkTL0L4NnHBayXXGjnL2A/xWwN3iH9Ih3VwDeeo2hmqN3AUZ5K5FrUqzFslkNaaCrH77ynyiyD759OvQ9owd5FHAQZGuFhSi6G4X7Ay+QNcm1TBwoVqRNcaazU4ERS7twsaQnSlhQTag5klmUDi3yZfd3wY3rSfH++NGE0uExleqhNcyPeB6R6OC9QjBlQlsldkcQo2I7ArP+J0hc653cHg74XinnwFL2WaMNPPlHmo0GJWXnqnBo0WbNf5qNQnTJIvQ2FvafSzH8pXkKJvgunS5k5unYbsEQWMPm77VUSs/W20ILxz52t68R00HrKbBqm+R/My0F0uiJIvjOlag3wkZE3L9oY5jieB1NTuWzcD446cZX3j1R7wQm7nGA9YWwL6rjd9mc42QuuLTH7CSru3UXV5VC2J+gJj0LGdHWprUX8zeTt1/rmqpN84abpRTm4nIPMbRPB8ek6fdcR/JbUENLd8TFKYgBB7i03Em3Eg3oKQK9z5DSvCEocwJSfPuXRaA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
